# 
version: '3.1'
services:
  db:
    image: mysql
    restart: always
    container_name: water-nestjs-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      # MYSQL_DATABASE: test
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    
    ports:
      - 3307:3306

  adminer:
    image: adminer
    container_name: water-nestjs-adminer
    restart: always
    ports:
      - 8081:8080